// ================================================================
//  app.js – Полная логика МТО v4.0 (все функции, PDF, права, расписание)
// ================================================================

(function(){'use strict';

// ------ Хранилище ------
const S={users:'mto_users',requests:'mto_requests',routes:'mto_routes',procurement:'mto_procurement',audit:'mto_audit',currentUser:'mto_current_user',materials:'mto_materials',supplies:'mto_supplies',schedule:'mto_schedule',settings:'mto_settings',repairs:'mto_repairs'};
function g(k){try{return JSON.parse(localStorage.getItem(k))||[]}catch(e){return[]}}
function s(k,v){localStorage.setItem(k,JSON.stringify(v))}

// ------ IndexedDB для чата ------
let db=null;const DB_NAME='MTOChatDB',DB_VERSION=1;
function openDB(){return new Promise((resolve,reject)=>{if(db){resolve(db);return}const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains('messages')){const st=d.createObjectStore('messages',{keyPath:'id'});st.createIndex('room','room',{unique:false});st.createIndex('timestamp','timestamp',{unique:false})}};r.onsuccess=e=>{db=e.target.result;resolve(db)};r.onerror=e=>reject(e.target.error)})}
async function saveMsg(room,msg){const db=await openDB();const tx=db.transaction('messages','readwrite');const st=tx.objectStore('messages');st.add({...msg,room,id:Date.now()+'_'+Math.random().toString(36).slice(2,6)});return new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=e=>reject(e.target.error)})}
async function getMsgs(room){const db=await openDB();const tx=db.transaction('messages','readonly');const st=tx.objectStore('messages');const idx=st.index('room');return new Promise((resolve,reject)=>{const r=idx.getAll(room);r.onsuccess=()=>resolve(r.result);r.onerror=e=>reject(e.target.error)})}

// ------ Дерево подразделений ------
const DEPT_TREE={name:'Корень',children:[{name:'Диспетчерская'},{name:'Склад',children:[{name:'Начальник склада'},{name:'Техническая служба'},{name:'Транспортная служба'},{name:'Кладовщик'}]},{name:'Участок 1'},{name:'Участок 2'},{name:'Участок 3'},{name:'Участок 4'},{name:'Участок 5'},{name:'Участок 6'},{name:'Участок 7'},{name:'Участок 8'},{name:'Администрация',children:[{name:'Управление МТО'},{name:'ГБУ Жилищник'},{name:'Директор'}]}]};
function getAllPaths(tree,prefix=''){let paths=[];const cur=prefix?prefix+' / '+tree.name:tree.name;if(tree.children){for(const child of tree.children)paths=paths.concat(getAllPaths(child,cur))}else paths.push(cur);return paths}
function getDeptList(){return getAllPaths(DEPT_TREE).filter(p=>p!=='Корень')}

// ------ Инициализация демо-данных ------
if(!localStorage.getItem(S.users))s(S.users,[
{login:'admin',password:'admin',displayName:'Администратор',phone:'+7-999-111-22-33',email:'admin@mto.ru',position:'Главный',birthDate:'1980-01-01',avatar:'',deptPath:'Администрация / ГБУ Жилищник'},
{login:'manager',password:'manager',displayName:'Менеджер',phone:'+7-999-222-33-44',email:'manager@mto.ru',position:'Менеджер',birthDate:'1990-05-15',avatar:'',deptPath:'Склад / Начальник склада'},
{login:'dispatcher',password:'dispatcher',displayName:'Диспетчер',phone:'+7-999-333-44-55',email:'disp@mto.ru',position:'Диспетчер',birthDate:'1985-08-20',avatar:'',deptPath:'Диспетчерская'},
{login:'analyst',password:'analyst',displayName:'Аналитик',phone:'+7-999-444-55-66',email:'analyst@mto.ru',position:'Аналитик',birthDate:'1992-12-01',avatar:'',deptPath:'Участок 1'}
]);
if(!localStorage.getItem(S.requests))s(S.requests,[
{id:1,title:'Замена масла в ГАЗели',desc:'Плановое ТО',type:'repair',address:'ул. Ленина, 5',deptPath:'Склад / Техническая служба',status:'work',priority:'medium',creator:'admin',deadline:'2026-08-10',responsible:'admin',created:Date.now()-3600000,updated:Date.now()},
{id:2,title:'Поставка труб',desc:'Для ремонта теплосетей',type:'supply',address:'пр. Мира, 12',deptPath:'Склад / Начальник склада',status:'new',priority:'high',creator:'manager',deadline:'2026-08-15',responsible:'manager',created:Date.now()-7200000,updated:Date.now()},
{id:3,title:'Ремонт ходовой КАМАЗа',desc:'Замена рессор',type:'repair',address:'ул. Транспортная, 8',deptPath:'Участок 3',status:'done',priority:'high',creator:'dispatcher',deadline:'2026-08-05',responsible:'dispatcher',created:Date.now()-86400000,updated:Date.now()-3600000}
]);
if(!localStorage.getItem(S.routes))s(S.routes,[
{id:1,vehicle:'ГАЗель NEXT',type:'supply',from:'Склад (ул. Ленина, 5)',to:'ул. Мира, 12',status:'inprogress',date:'2026-08-03'},
{id:2,vehicle:'КАМАЗ-65115',type:'transport',from:'Диспетчерская',to:'Участок 3',status:'planned',date:'2026-08-04'}
]);
if(!localStorage.getItem(S.procurement))s(S.procurement,[
{id:1,name:'Закупка масла',type:'grant',supplier:'ООО "Нефть-Трейд"',amount:150000,status:'process',date:'2026-08-02',number:'Г-2026-001'},
{id:2,name:'Закупка фильтров',type:'competition',supplier:'ЗАО "Автодеталь"',amount:75000,status:'planned',date:'2026-08-10',number:'К-2026-002'}
]);
if(!localStorage.getItem(S.audit))s(S.audit,[]);
if(!localStorage.getItem(S.materials))s(S.materials,[
{id:1,name:'Масло моторное',category:'ГСМ',unit:'л',quantity:100,reserve:20},
{id:2,name:'Фильтр масляный',category:'Для машины',unit:'шт',quantity:50,reserve:10},
{id:3,name:'Краска белая',category:'Краска',unit:'кг',quantity:30,reserve:5},
{id:4,name:'Цемент',category:'Сыпучие',unit:'меш',quantity:200,reserve:40},
{id:5,name:'Дрель',category:'Инструмент',unit:'шт',quantity:15,reserve:2}
]);
if(!localStorage.getItem(S.supplies))s(S.supplies,[
{id:1,material:'Масло моторное',quantity:50,date:new Date(Date.now()-86400000).toLocaleString(),type:'приход'},
{id:2,material:'Фильтр масляный',quantity:20,date:new Date(Date.now()-172800000).toLocaleString(),type:'приход'}
]);
if(!localStorage.getItem(S.schedule)){const us=g(S.users);const sch={};us.forEach(u=>{sch[u.login]={mon:'day',tue:'day',wed:'day',thu:'day',fri:'day',sat:'off',sun:'off'}});s(S.schedule,sch)}
if(!localStorage.getItem(S.settings))s(S.settings,{theme:'light',notifications:true,compact:false,animations:true,language:'ru',fontSize:14});
if(!localStorage.getItem(S.repairs))s(S.repairs,[
{id:1,vehicle:'КАМАЗ-65115',reason:'Поломка коробки передач',startDate:'2026-08-01',status:'в работе'},
{id:2,vehicle:'ГАЗель NEXT',reason:'Замена двигателя',startDate:'2026-08-03',status:'ожидание запчастей'}
]);

// ------ Вспомогательные ------
function genId(){return Date.now()+Math.floor(Math.random()*1000)}
function logAudit(user,action,details){const logs=g(S.audit);logs.push({time:new Date().toLocaleString(),user,action,details});s(S.audit,logs)}
function showToast(msg,type='info'){const c=document.getElementById('toastContainer');const t=document.createElement('div');t.className='toast '+type;t.innerHTML='<span>'+msg+'</span><button class="close-toast">&times;</button>';c.appendChild(t);t.querySelector('.close-toast').onclick=()=>t.remove();setTimeout(()=>t.remove(),5000)}
function getStatusBadge(st){const map={new:'Новая',work:'В работе',done:'Выполнена',rejected:'Отклонена',planned:'Запланирована',process:'В процессе'};const cls=st==='new'?'new':st==='work'?'work':st==='done'?'done':st==='rejected'?'rejected':st==='planned'?'planned':'process';return '<span class="status-badge status-'+cls+'">'+(map[st]||st)+'</span>'}
function getPriorityLabel(p){const map={low:'Низкий',medium:'Средний',high:'Высокий'};return map[p]||p}
function isAdmin(user){if(!user)return false;if(user.login==='admin')return true;if(user.deptPath&&user.deptPath.includes('Администрация'))return true;return false}
function getUserRole(user){if(!user)return 'guest';if(isAdmin(user))return 'admin';if(user.deptPath&&user.deptPath.includes('Начальник склада'))return 'warehouse';if(user.deptPath&&user.deptPath.includes('Диспетчерская'))return 'dispatcher';return 'employee'}

// ------ Аутентификация ------
let currentUser=null;
function loadSession(){const st=localStorage.getItem(S.currentUser);if(st){try{currentUser=JSON.parse(st);return true}catch(e){return false}}return false}
function saveSession(u){localStorage.setItem(S.currentUser,JSON.stringify(u))}
function loginUser(login,password){const users=g(S.users);const found=users.find(u=>u.login===login&&u.password===password);if(found){currentUser=found;saveSession(found);logAudit(login,'Вход в систему','Успешный вход');showToast('Добро пожаловать, '+(found.displayName||login)+'!','success');if('Notification' in window&&Notification.permission==='default')Notification.requestPermission();return true}return false}
function registerUser(login,password,deptPath,displayName,phone,email,position,birthDate,avatarBase64){const users=g(S.users);if(users.find(u=>u.login===login))return false;const newUser={login,password,displayName:displayName||login,phone:phone||'',email:email||'',position:position||'',birthDate:birthDate||'',avatar:avatarBase64||'',deptPath:deptPath||'Диспетчерская'};users.push(newUser);s(S.users,users);logAudit(login,'Регистрация','Новый пользователь');const sch=g(S.schedule);sch[login]={mon:'day',tue:'day',wed:'day',thu:'day',fri:'day',sat:'off',sun:'off'};s(S.schedule,sch);return true}
function logoutUser(){if(currentUser)logAudit(currentUser.login,'Выход','');currentUser=null;localStorage.removeItem(S.currentUser);showToast('Вы вышли','info')}
function oauthLogin(provider){const fakeLogin='user_'+provider+'_'+Date.now().toString(36);const fakePassword='pass_'+Math.random().toString(36);const users=g(S.users);let existing=users.find(u=>u.login===fakeLogin);if(!existing)registerUser(fakeLogin,fakePassword,'Диспетчерская','Пользователь '+provider,'','','','','');loginUser(fakeLogin,fakePassword);document.getElementById('authOverlay').classList.add('hidden');initAppAfterLogin();showToast('Вход через '+provider+' выполнен','success')}

// ------ Заявки ------
function getRequests(){return g(S.requests)}
function saveRequests(r){s(S.requests,r)}
function createRequest(title,desc,type,address,deptPath,priority,status,deadline,creator,responsible){const reqs=getRequests();const newReq={id:genId(),title,desc,type,address,deptPath,priority,status,deadline,creator,responsible:responsible||creator,created:Date.now(),updated:Date.now()};reqs.push(newReq);saveRequests(reqs);logAudit(creator,'Создание заявки','#'+newReq.id+' "'+title+'"');showToast('Заявка #'+newReq.id+' создана','success');return newReq}
function updateRequest(id,data){const reqs=getRequests();const idx=reqs.findIndex(r=>r.id===id);if(idx===-1)return false;const old=reqs[idx];reqs[idx]={...old,...data,updated:Date.now()};saveRequests(reqs);logAudit(currentUser.login,'Изменение заявки','#'+id+' "'+old.title+'"');showToast('Заявка #'+id+' обновлена','info');return true}
function deleteRequest(id){let reqs=getRequests();const found=reqs.find(r=>r.id===id);if(!found)return false;reqs=reqs.filter(r=>r.id!==id);saveRequests(reqs);logAudit(currentUser.login,'Удаление заявки','#'+id+' "'+found.title+'"');showToast('Заявка #'+id+' удалена','error');return true}

// ------ Маршруты ------
function getRoutes(){return g(S.routes)}
function saveRoutes(r){s(S.routes,r)}
function createRoute(vehicle,type,from,to,status,date){const routes=getRoutes();const newRoute={id:genId(),vehicle,type,from,to,status,date};routes.push(newRoute);saveRoutes(routes);logAudit(currentUser.login,'Создание маршрута',vehicle+' → '+to);showToast('Маршрут для '+vehicle+' создан','success');return newRoute}
function updateRoute(id,data){const routes=getRoutes();const idx=routes.findIndex(r=>r.id===id);if(idx===-1)return false;routes[idx]={...routes[idx],...data};saveRoutes(routes);logAudit(currentUser.login,'Изменение маршрута','#'+id);showToast('Маршрут обновлён','info');return true}
function deleteRoute(id){let routes=getRoutes();const found=routes.find(r=>r.id===id);if(!found)return false;routes=routes.filter(r=>r.id!==id);saveRoutes(routes);logAudit(currentUser.login,'Удаление маршрута','#'+id);showToast('Маршрут удалён','error');return true}
function getRepairs(){return g(S.repairs)}
function saveRepairs(r){s(S.repairs,r)}
function addRepair(vehicle,reason,startDate,status){const repairs=getRepairs();const newRep={id:genId(),vehicle,reason,startDate,status};repairs.push(newRep);saveRepairs(repairs);logAudit(currentUser.login,'Добавление ремонта',vehicle);showToast('Ремонт для '+vehicle+' добавлен','success');return newRep}
function completeRepair(id){let repairs=getRepairs();const found=repairs.find(r=>r.id===id);if(!found)return false;repairs=repairs.filter(r=>r.id!==id);saveRepairs(repairs);logAudit(currentUser.login,'Завершение ремонта',found.vehicle);showToast('Ремонт '+found.vehicle+' завершён','success');return true}

// ------ Закупки (гранты, конкурсы) ------
function getProcurements(){return g(S.procurement)}
function saveProcurements(p){s(S.procurement,p)}
function createProcurement(name,type,supplier,amount,status,date,number){const procs=getProcurements();const newProc={id:genId(),name,type,supplier,amount:parseFloat(amount)||0,status,date,number:number||''};procs.push(newProc);saveProcurements(procs);logAudit(currentUser.login,'Создание закупки',name+' ('+supplier+')');showToast('Закупка "'+name+'" создана','success');return newProc}
function updateProcurement(id,data){const procs=getProcurements();const idx=procs.findIndex(p=>p.id===id);if(idx===-1)return false;procs[idx]={...procs[idx],...data};saveProcurements(procs);logAudit(currentUser.login,'Изменение закупки','#'+id+' '+procs[idx].name);showToast('Закупка обновлена','info');return true}
function deleteProcurement(id){let procs=getProcurements();const found=procs.find(p=>p.id===id);if(!found)return false;procs=procs.filter(p=>p.id!==id);saveProcurements(procs);logAudit(currentUser.login,'Удаление закупки',found.name);showToast('Закупка "'+found.name+'" удалена','error');return true}

// ------ Материалы ------
function getMaterials(){return g(S.materials)}
function saveMaterials(m){s(S.materials,m)}
function getSupplies(){return g(S.supplies)}
function saveSupplies(sup){s(S.supplies,sup)}
function addMaterial(name,category,unit,quantity,reserve){const mats=getMaterials();const newMat={id:genId(),name,category,unit,quantity:parseInt(quantity)||0,reserve:parseInt(reserve)||0};mats.push(newMat);saveMaterials(mats);logAudit(currentUser.login,'Добавление материала',name+' ('+category+')');showToast('Материал "'+name+'" добавлен','success');return newMat}
function updateMaterial(id,data){const mats=getMaterials();const idx=mats.findIndex(m=>m.id===id);if(idx===-1)return false;mats[idx]={...mats[idx],...data};saveMaterials(mats);logAudit(currentUser.login,'Изменение материала','#'+id+' '+mats[idx].name);showToast('Материал обновлён','info');return true}
function deleteMaterial(id){let mats=getMaterials();const found=mats.find(m=>m.id===id);if(!found)return false;mats=mats.filter(m=>m.id!==id);saveMaterials(mats);logAudit(currentUser.login,'Удаление материала',found.name);showToast('Материал "'+found.name+'" удалён','error');return true}
function addSupply(materialName,quantity){const supplies=getSupplies();const newSup={id:genId(),material:materialName,quantity:parseInt(quantity)||0,date:new Date().toLocaleString(),type:'приход'};supplies.push(newSup);saveSupplies(supplies);const mats=getMaterials();const mat=mats.find(m=>m.name===materialName);if(mat){mat.quantity+=parseInt(quantity)||0;saveMaterials(mats)}logAudit(currentUser.login,'Поставка материала',materialName+' +'+quantity);showToast('Поставка '+materialName+' +'+quantity,'success');return newSup}
function reserveMaterial(id,amount){const mats=getMaterials();const mat=mats.find(m=>m.id===id);if(!mat)return false;const avail=mat.quantity-mat.reserve;if(avail<amount){showToast('Недостаточно доступного количества','error');return false}mat.reserve+=amount;saveMaterials(mats);logAudit(currentUser.login,'Резервирование материала',mat.name+' +'+amount);showToast('Зарезервировано '+amount+' '+mat.unit,'info');return true}
function issueMaterial(id,amount){const mats=getMaterials();const mat=mats.find(m=>m.id===id);if(!mat)return false;const avail=mat.quantity-mat.reserve;if(avail<amount){showToast('Недостаточно доступного количества','error');return false}mat.quantity-=amount;saveMaterials(mats);logAudit(currentUser.login,'Выдача материала',mat.name+' -'+amount);showToast('Выдано '+amount+' '+mat.unit,'info');return true}

// ------ Расписание ------
function getSchedule(){return g(S.schedule)}
function saveSchedule(sch){s(S.schedule,sch)}

// ------ Новости (Яндекс) ------
async function fetchNews(limit=5,containerId='newsFeedList'){const c=document.getElementById(containerId);if(c)c.innerHTML='Загрузка...';try{const proxy='https://api.allorigins.win/raw?url=';const rss='https://news.yandex.ru/news.rss';const resp=await fetch(proxy+encodeURIComponent(rss));if(!resp.ok)throw new Error('Ошибка');const txt=await resp.text();const parser=new DOMParser();const xml=parser.parseFromString(txt,'text/xml');const items=xml.querySelectorAll('item');let html='';let count=0;items.forEach(item=>{if(count>=limit)return;const title=item.querySelector('title')?.textContent||'Без названия';const pub=item.querySelector('pubDate')?.textContent||'';const link=item.querySelector('link')?.textContent||'#';html+='<div class="news-item"><div class="title"><a href="'+link+'" target="_blank" style="color:var(--primary);text-decoration:none;">'+title+'</a></div><div class="date">'+pub+'</div></div>';count++});if(c)c.innerHTML=html||'<p style="color:var(--text-secondary);">Новостей нет</p>'}catch(e){if(c)c.innerHTML='<p style="color:var(--text-secondary);">Не удалось загрузить новости</p>'}}

// ------ Погода с прогнозом ------
async function fetchWeather(city='Moscow'){const temp=document.getElementById('weatherTemp');const desc=document.getElementById('weatherDesc');const cityEl=document.getElementById('weatherCity');const fore=document.getElementById('weatherForecast');try{const key='e3e0f9f7f0e5d4c3b2a10987654321';const url=`https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${key}&units=metric&lang=ru`;const resp=await fetch(url);if(!resp.ok)throw new Error('Город не найден');const data=await resp.json();temp.textContent=Math.round(data.main.temp)+'°C';desc.textContent=data.weather[0].description;cityEl.textContent=data.name;const fUrl=`https://api.openweathermap.org/data/2.5/forecast?q=${city}&appid=${key}&units=metric&lang=ru&cnt=5`;const fResp=await fetch(fUrl);if(fResp.ok){const fData=await fResp.json();const days=fData.list.slice(0,5);fore.innerHTML=days.map(d=>{const date=new Date(d.dt*1000).toLocaleDateString('ru-RU',{weekday:'short',day:'numeric'});return '<div class="day"><div class="date">'+date+'</div><div class="temp">'+Math.round(d.main.temp)+'°</div><div style="font-size:12px;color:var(--text-secondary);">'+d.weather[0].description+'</div></div>'}).join('')}else fore.innerHTML=''}catch(e){temp.textContent='--°C';desc.textContent='Ошибка';cityEl.textContent=city;fore.innerHTML=''}}

// ------ Карта ------
function initMaps(){if(typeof ymaps==='undefined')return;ymaps.ready(()=>{const mapCmto=new ymaps.Map('mapCmto',{center:[55.733073,37.396815],zoom:16,controls:['zoomControl','fullscreenControl']});const cmtoPoint=new ymaps.Placemark([55.733073,37.396815],{balloonContent:'ЦМТО'},{preset:'islands#blueDotIcon'});mapCmto.geoObjects.add(cmtoPoint);const mapHead=new ymaps.Map('mapHead',{center:[55.733629,37.401594],zoom:16,controls:['zoomControl','fullscreenControl']});const headPoint=new ymaps.Placemark([55.733629,37.401594],{balloonContent:'Главный корпус МТО'},{preset:'islands#redDotIcon'});mapHead.geoObjects.add(headPoint)})}

// ------ ДАННЫЕ ДЛЯ ДАШБОРДА ------
const deptData={'default':{label:'Общая',stats:{orders:78,transport:24,employees:18,completed:62},recentOrders:['Рейс #1023 – доставка запчастей','Рейс #1022 – вывоз мусора','Рейс #1021 – ТО автопарка'],kpi:[{label:'Выполнение рейсов',value:'89%'},{label:'Среднее время',value:'2.1 ч'},{label:'Загрузка',value:'76%'}],activity:['ГАЗель – в пути','КАМАЗ – на погрузке','МАЗ – в рейсе'],erpLog:['Рейс #1023 завершён','Обновлён график ТО','Замена масла в ГАЗели'],transportList:[{name:'ГАЗель NEXT',plate:'А123ВВ',status:'В пути',color:'#2ecc71'},{name:'КАМАЗ-65115',plate:'В456СС',status:'На погрузке',color:'#f39c12'},{name:'МАЗ-5440',plate:'С789ММ',status:'В рейсе',color:'#3498db'},{name:'MAN TGS',plate:'Р012РР',status:'На ТО',color:'#e74c3c'}],transportStats:{total:24,enRoute:12,loading:5,maintenance:4,idle:3}}};

// ------ РЕНДЕРИНГ ------
const statsContainer=document.getElementById('statsContainer');
const recentOrders=document.getElementById('recentOrders');
const kpiGrid=document.getElementById('kpiGrid');
const activityList=document.getElementById('activityList');
const erpLogItems=document.getElementById('erpLogItems');
const transportGrid=document.getElementById('transportGrid');
const auditBody=document.getElementById('auditBody');
const requestsBody=document.getElementById('requestsBody');
const routesBody=document.getElementById('routesBody');
const materialsBody=document.getElementById('materialsBody');
const procurementBody=document.getElementById('procurementBody');
const scheduleContainer=document.getElementById('scheduleContainer');
const repairContainer=document.getElementById('repairVehicles');
const userNameDisplay=document.getElementById('userName');
const logoutBtn=document.getElementById('logoutBtn');
const chatMessagesContainer=document.getElementById('chatMessages');
const chatInput=document.getElementById('chatInput');
const chatSendBtn=document.getElementById('chatSendBtn');
const chatRooms=document.querySelectorAll('.chat-room-item');

function populateDeptSelects(){const paths=getDeptList();const selects=document.querySelectorAll('#authDeptPath, #profileDeptPath, #reqDept');selects.forEach(sel=>{const cur=sel.value;sel.innerHTML='';paths.forEach(p=>{const opt=document.createElement('option');opt.value=p;opt.textContent=p;sel.appendChild(opt)});if(cur&&paths.includes(cur))sel.value=cur})}

function renderDashboard(){const data=deptData['default'];const s=data.stats;statsContainer.innerHTML='<div class="mto-stat"><h1>'+s.orders+'</h1><p>Заявок</p></div><div class="mto-stat"><h1>'+s.transport+'</h1><p>Транспорт</p></div><div class="mto-stat"><h1>'+s.employees+'</h1><p>Сотрудников</p></div><div class="mto-stat"><h1>'+s.completed+'</h1><p>Выполнено</p></div>';recentOrders.innerHTML=data.recentOrders.map(i=>'<li>'+i+'</li>').join('');kpiGrid.innerHTML=data.kpi.map(k=>'<div class="mto-kpi-item"><h4>'+k.label+'</h4><div class="value">'+k.value+'</div></div>').join('');activityList.innerHTML=data.activity.map(i=>'<li>'+i+'</li>').join('');erpLogItems.innerHTML=data.erpLog.map(i=>'<div class="mto-erp-log-item">'+i+'</div>').join('');fetchNews(5,'newsFeedList');fetchWeather('Moscow');setTimeout(initMaps,500);renderMyTasks();renderCalendar()}

function renderMyTasks(){const container=document.getElementById('myTasks');if(!currentUser){container.innerHTML='Войдите для просмотра';return}const reqs=getRequests().filter(r=>r.responsible===currentUser.login||r.creator===currentUser.login);if(!reqs.length){container.innerHTML='Нет активных задач';return}container.innerHTML=reqs.slice(0,5).map(r=>'<div style="padding:6px 0;border-bottom:1px solid rgba(0,0,0,0.04);">#'+r.id+' '+r.title+' — '+getStatusBadge(r.status)+'</div>').join('')}

function renderCalendar(){const container=document.getElementById('calendarWidget');const now=new Date();const year=now.getFullYear();const month=now.getMonth();const first=new Date(year,month,1);const last=new Date(year,month+1,0);const days=[];for(let d=1;d<=last.getDate();d++)days.push(new Date(year,month,d));let html='';days.forEach(d=>{const isToday=d.toDateString()===now.toDateString();const isWeekend=d.getDay()===0||d.getDay()===6;html+='<div class="day'+(isToday?' today':'')+(isWeekend?' weekend':'')+'">'+d.getDate()+'</div>'});container.innerHTML=html}

function renderTransport(){const data=deptData['default'];if(data.transportList.length){transportGrid.innerHTML=data.transportList.map(t=>'<div class="mto-card"><h3>'+t.name+'</h3><p style="color:var(--text-secondary);">'+t.plate+'</p><span class="mto-vehicle-tag" style="background:'+t.color+'">'+t.status+'</span></div>').join('')}else transportGrid.innerHTML='<p style="grid-column:1/-1;text-align:center;color:var(--text-secondary);">Нет транспорта</p>';renderRoutes();renderRepairVehicles()}
function renderRoutes(){const filter=document.getElementById('routeFilterStatus').value;let routes=getRoutes();if(filter!=='all')routes=routes.filter(r=>r.status===filter);if(!routes.length){routesBody.innerHTML='<tr><td colspan="7" style="text-align:center;color:var(--text-secondary);">Нет маршрутов</td></tr>';return}routesBody.innerHTML=routes.map(r=>'<tr><td>'+r.vehicle+'</td><td><span class="route-tag">'+(r.type==='supply'?'Поставка':r.type==='shipment'?'Отправка':'Перевоз')+'</span></td><td>'+r.from+'</td><td>'+r.to+'</td><td>'+getStatusBadge(r.status)+'</td><td>'+r.date+'</td><td><button class="btn btn-warning btn-sm edit-route" data-id="'+r.id+'">✏️</button><button class="btn btn-danger btn-sm delete-route" data-id="'+r.id+'">🗑️</button></td></tr>').join('');document.querySelectorAll('.edit-route').forEach(b=>b.addEventListener('click',function(){openEditRoute(parseInt(this.dataset.id))}));document.querySelectorAll('.delete-route').forEach(b=>b.addEventListener('click',function(){if(confirm('Удалить маршрут?')){deleteRoute(parseInt(this.dataset.id));renderRoutes()}}))}
function renderRepairVehicles(){const repairs=getRepairs();if(!repairs.length){repairContainer.innerHTML='<p>Нет техники на ремонте</p>';return}repairContainer.innerHTML=repairs.map(r=>'<div class="mto-card"><h3>'+r.vehicle+'</h3><p>Причина: '+r.reason+'</p><p>Начало: '+r.startDate+'</p><p>Статус: '+r.status+'</p><button class="btn btn-warning btn-sm" onclick="completeRepair('+r.id+')">Завершить</button><button class="btn btn-primary btn-sm" onclick="createRepairRequest('+r.id+')">Заявка на ремонт</button></div>').join('')}
window.completeRepair=function(id){completeRepair(id);renderRepairVehicles()};
window.createRepairRequest=function(id){const repairs=getRepairs();const found=repairs.find(r=>r.id===id);if(!found)return;createRequest('Ремонт '+found.vehicle,'Причина: '+found.reason,'repair','',currentUser.deptPath,'high','new',new Date().toISOString().split('T')[0],currentUser.login,currentUser.login);showToast('Заявка на ремонт создана','success')};

function renderRequests(){const statusFilter=document.getElementById('reqFilterStatus').value;const typeFilter=document.getElementById('reqFilterType').value;let reqs=getRequests();if(statusFilter!=='all')reqs=reqs.filter(r=>r.status===statusFilter);if(typeFilter!=='all')reqs=reqs.filter(r=>r.type===typeFilter);if(currentUser&&!isAdmin(currentUser)){reqs=reqs.filter(r=>r.deptPath===currentUser.deptPath||r.creator===currentUser.login||r.responsible===currentUser.login)}if(!reqs.length){requestsBody.innerHTML='<tr><td colspan="8" style="text-align:center;color:var(--text-secondary);">Нет заявок</td></tr>';return}requestsBody.innerHTML=reqs.map(r=>'<tr><td>#'+r.id+'</td><td>'+r.title+'</td><td>'+(r.type==='repair'?'Ремонт':r.type==='supply'?'Поставка':r.type==='transport'?'Перевозка':'Другое')+'</td><td>'+getStatusBadge(r.status)+'</td><td class="'+getPriorityClass(r.priority)+'">'+getPriorityLabel(r.priority)+'</td><td>'+(r.responsible||'—')+'</td><td>'+(canEditRequest(r)?'<button class="btn btn-primary btn-sm edit-req" data-id="'+r.id+'">✏️</button>':'')+(canDeleteRequest(r)?'<button class="btn btn-danger btn-sm delete-req" data-id="'+r.id+'">🗑️</button>':'')+(canChangeStatus(r)?'<select class="status-change" data-id="'+r.id+'"><option value="new">Новая</option><option value="work">В работе</option><option value="done">Выполнена</option><option value="rejected">Отклонена</option></select>':'')+'<button class="btn btn-success btn-sm pdf-req" data-id="'+r.id+'">PDF</button></td></tr>').join('');document.querySelectorAll('.edit-req').forEach(b=>b.addEventListener('click',function(){openEditRequest(parseInt(this.dataset.id))}));document.querySelectorAll('.delete-req').forEach(b=>b.addEventListener('click',function(){if(confirm('Удалить заявку?')){deleteRequest(parseInt(this.dataset.id));renderRequests()}}));document.querySelectorAll('.status-change').forEach(sel=>sel.addEventListener('change',function(){const id=parseInt(this.dataset.id);const newStatus=this.value;updateRequest(id,{status:newStatus});renderRequests()}));document.querySelectorAll('.pdf-req').forEach(b=>b.addEventListener('click',function(){exportRequestPDF(parseInt(this.dataset.id))}))}
function canEditRequest(req){if(!currentUser)return false;if(isAdmin(currentUser))return true;if(currentUser.deptPath===req.deptPath)return true;return false}
function canDeleteRequest(req){if(!currentUser)return false;if(isAdmin(currentUser))return true;if(currentUser.login===req.creator)return true;return false}
function canChangeStatus(req){if(!currentUser)return false;if(isAdmin(currentUser))return true;if(currentUser.deptPath===req.deptPath||currentUser.login===req.responsible)return true;return false}

function renderMaterials(){const catFilter=document.getElementById('matCategoryFilter').value;let mats=getMaterials();if(catFilter!=='all')mats=mats.filter(m=>m.category===catFilter);if(!mats.length){materialsBody.innerHTML='<tr><td colspan="7" style="text-align:center;color:var(--text-secondary);">Нет материалов</td></tr>';return}materialsBody.innerHTML=mats.map(m=>'<tr><td>'+m.name+'</td><td><span class="category-tag">'+m.category+'</span></td><td>'+m.unit+'</td><td>'+m.quantity+'</td><td>'+m.reserve+'</td><td>'+(m.quantity-m.reserve)+'</td><td><button class="btn btn-warning btn-sm edit-mat" data-id="'+m.id+'">✏️</button><button class="btn btn-danger btn-sm delete-mat" data-id="'+m.id+'">🗑️</button><button class="btn btn-success btn-sm issue-mat" data-id="'+m.id+'">Выдать</button><button class="btn btn-primary btn-sm reserve-mat" data-id="'+m.id+'">Резерв</button><button class="btn btn-success btn-sm pdf-mat" data-id="'+m.id+'">PDF</button></td></tr>').join('');document.querySelectorAll('.edit-mat').forEach(b=>b.addEventListener('click',function(){openEditMaterial(parseInt(this.dataset.id))}));document.querySelectorAll('.delete-mat').forEach(b=>b.addEventListener('click',function(){if(confirm('Удалить материал?')){deleteMaterial(parseInt(this.dataset.id));renderMaterials()}}));document.querySelectorAll('.issue-mat').forEach(b=>b.addEventListener('click',function(){const id=parseInt(this.dataset.id);const amount=prompt('Введите количество для выдачи:');if(amount&&!isNaN(amount)&&Number(amount)>0){issueMaterial(id,Number(amount));renderMaterials()}}));document.querySelectorAll('.reserve-mat').forEach(b=>b.addEventListener('click',function(){const id=parseInt(this.dataset.id);const amount=prompt('Введите количество для резервирования:');if(amount&&!isNaN(amount)&&Number(amount)>0){reserveMaterial(id,Number(amount));renderMaterials()}}));document.querySelectorAll('.pdf-mat').forEach(b=>b.addEventListener('click',function(){exportMaterialPDF(parseInt(this.dataset.id))}))}

function renderProcurements(){const statusFilter=document.getElementById('procurementFilterStatus').value;let procs=getProcurements();if(statusFilter!=='all')procs=procs.filter(p=>p.status===statusFilter);if(!procs.length){procurementBody.innerHTML='<tr><td colspan="7" style="text-align:center;color:var(--text-secondary);">Нет закупок</td></tr>';return}procurementBody.innerHTML=procs.map(p=>'<tr><td>'+p.name+'</td><td>'+(p.type==='grant'?'Грант':p.type==='competition'?'Конкурс':'Прямой договор')+'</td><td>'+p.supplier+'</td><td>'+(p.amount?p.amount.toLocaleString()+' руб.':'—')+'</td><td>'+getStatusBadge(p.status)+'</td><td>'+p.date+'</td><td><button class="btn btn-warning btn-sm edit-proc" data-id="'+p.id+'">✏️</button><button class="btn btn-danger btn-sm delete-proc" data-id="'+p.id+'">🗑️</button><button class="btn btn-success btn-sm pdf-proc" data-id="'+p.id+'">PDF</button></td></tr>').join('');document.querySelectorAll('.edit-proc').forEach(b=>b.addEventListener('click',function(){openEditProcurement(parseInt(this.dataset.id))}));document.querySelectorAll('.delete-proc').forEach(b=>b.addEventListener('click',function(){if(confirm('Удалить закупку?')){deleteProcurement(parseInt(this.dataset.id));renderProcurements()}}));document.querySelectorAll('.pdf-proc').forEach(b=>b.addEventListener('click',function(){exportProcurementPDF(parseInt(this.dataset.id))}))}

function renderSchedule(){const container=scheduleContainer;container.innerHTML='';if(!currentUser){container.innerHTML='<p>Войдите для просмотра</p>';return}if(isAdmin(currentUser)){const users=g(S.users);const schedule=getSchedule();const days=['mon','tue','wed','thu','fri','sat','sun'];const dayLabels=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];const shifts=['day','night','off','remote','sick','vacation'];const shiftLabels={day:'День',night:'Ночь',off:'Выходной',remote:'Удалёнка',sick:'Больничный',vacation:'Отпуск'};users.forEach(u=>{const div=document.createElement('div');div.className='schedule-user';div.innerHTML='<h4>'+(u.displayName||u.login)+'</h4><div class="schedule-grid">';div.innerHTML+='<div class="cell header">День</div>';dayLabels.forEach(d=>div.innerHTML+='<div class="cell header">'+d+'</div>');const s=schedule[u.login]||{};days.forEach(day=>{const val=s[day]||'off';div.innerHTML+='<div class="cell"><select class="schedule-select" data-user="'+u.login+'" data-day="'+day+'">'+shifts.map(sh=>'<option value="'+sh+'" '+(sh===val?'selected':'')+'>'+shiftLabels[sh]+'</option>').join('')+'</select></div>'});div.innerHTML+='</div>';container.appendChild(div)});document.getElementById('saveScheduleBtn').style.display='inline-block'}else{const schedule=getSchedule();const s=schedule[currentUser.login]||{};const days=['mon','tue','wed','thu','fri','sat','sun'];const dayLabels=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];const shiftLabels={day:'День',night:'Ночь',off:'Выходной',remote:'Удалёнка',sick:'Больничный',vacation:'Отпуск'};const div=document.createElement('div');div.className='schedule-user';div.innerHTML='<h4>Моё расписание</h4><div class="schedule-grid">';div.innerHTML+='<div class="cell header">День</div>';dayLabels.forEach(d=>div.innerHTML+='<div class="cell header">'+d+'</div>');days.forEach(day=>{const val=s[day]||'off';div.innerHTML+='<div class="cell">'+shiftLabels[val]+'</div>'});div.innerHTML+='</div>';container.appendChild(div);document.getElementById('saveScheduleBtn').style.display='none'}}

function renderAudit(){if(!isAdmin(currentUser)){auditBody.innerHTML='<tr><td colspan="4" style="text-align:center;color:var(--text-secondary);">Доступно только администратору</td></tr>';return}let logs=g(S.audit);const search=document.getElementById('auditSearch').value.toLowerCase();const userFilter=document.getElementById('auditFilterUser').value;const actionFilter=document.getElementById('auditFilterAction').value;if(search)logs=logs.filter(l=>l.user.toLowerCase().includes(search)||l.action.toLowerCase().includes(search)||(l.details||'').toLowerCase().includes(search));if(userFilter!=='all')logs=logs.filter(l=>l.user===userFilter);if(actionFilter!=='all')logs=logs.filter(l=>l.action===actionFilter);if(!logs.length){auditBody.innerHTML='<tr><td colspan="4" style="text-align:center;color:var(--text-secondary);">Нет записей</td></tr>';return}auditBody.innerHTML=logs.slice(-100).reverse().map(l=>'<tr><td>'+l.time+'</td><td>'+l.user+'</td><td>'+l.action+'</td><td>'+(l.details||'')+'</td></tr>').join('')}

// ------ ЧАТ ------
let currentChatRoom='general';
let chatMediaRecorder=null;let chatAudioChunks=[];
async function renderChat(room){const msgs=await getMsgs(room);chatMessagesContainer.innerHTML=msgs.map(msg=>{const isOwn=currentUser&&msg.sender===currentUser.login;let media='';if(msg.media){if(msg.mediaType==='image')media='<img src="'+msg.media+'" class="media-content" style="max-width:200px;border-radius:10px;">';else if(msg.mediaType==='video')media='<video src="'+msg.media+'" class="media-content" controls style="max-width:200px;border-radius:10px;"></video>';else if(msg.mediaType==='audio'||msg.mediaType==='voice')media='<audio src="'+msg.media+'" class="media-content" controls style="width:100%;"></audio>'}return '<div class="chat-message '+(isOwn?'own':'')+'">'+(msg.text?'<div>'+msg.text+'</div>':'')+media+'<div class="meta"><span>'+msg.sender+'</span><span>'+(msg.time||'')+'</span></div></div>'}).join('');chatMessagesContainer.scrollTop=chatMessagesContainer.scrollHeight}
async function sendChatMessage(text,media=null,mediaType=null){if(!currentUser){showToast('Войдите в систему','error');return}const roomKey=currentChatRoom==='personal'?'personal_'+currentUser.login:currentChatRoom;const msg={sender:currentUser.login,text:text||'',time:new Date().toLocaleTimeString(),timestamp:Date.now(),media,mediaType};await saveMsg(roomKey,msg);renderChat(roomKey);if('Notification' in window&&Notification.permission==='granted'){new Notification('Новое сообщение',{body:msg.sender+': '+(msg.text||'Медиа-файл')})}}
function switchChatRoom(room){currentChatRoom=room;chatRooms.forEach(el=>el.classList.remove('active'));document.querySelector('.chat-room-item[data-room="'+room+'"]').classList.add('active');const roomKey=room==='personal'?'personal_'+currentUser.login:room;renderChat(roomKey)}
function handleMediaCapture(type){if(!currentUser){showToast('Войдите в систему','error');return}const input=document.createElement('input');input.type='file';input.accept=type==='image'?'image/*':type==='video'?'video/*':'audio/*';if(type==='image'||type==='video')input.capture=type==='image'?'environment':'environment';input.onchange=async(e)=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=async(ev)=>{const base64=ev.target.result;await sendChatMessage('',base64,type);input.remove()};reader.readAsDataURL(file)};input.click()}
function toggleVoiceRecord(){if(!currentUser){showToast('Войдите в систему','error');return}if(chatMediaRecorder&&chatMediaRecorder.state==='recording'){chatMediaRecorder.stop();document.getElementById('voiceRecordBtn').classList.remove('active');return}navigator.mediaDevices.getUserMedia({audio:true}).then(stream=>{chatMediaRecorder=new MediaRecorder(stream);chatAudioChunks=[];chatMediaRecorder.ondataavailable=e=>chatAudioChunks.push(e.data);chatMediaRecorder.onstop=async()=>{const blob=new Blob(chatAudioChunks,{type:'audio/webm'});const reader=new FileReader();reader.onload=async(ev)=>{const base64=ev.target.result;await sendChatMessage('',base64,'voice');stream.getTracks().forEach(t=>t.stop())};reader.readAsDataURL(blob);document.getElementById('voiceRecordBtn').classList.remove('active')};chatMediaRecorder.start();document.getElementById('voiceRecordBtn').classList.add('active')}).catch(err=>showToast('Ошибка доступа к микрофону','error'))}

// ------ ПОИСК ------
function globalSearch(query){if(!query.trim())return [];const q=query.toLowerCase();const results=[];getRequests().forEach(r=>{if(r.title.toLowerCase().includes(q)||r.desc.toLowerCase().includes(q)||r.creator.toLowerCase().includes(q))results.push({type:'Заявка',id:r.id,title:r.title,section:'requests'})});getRoutes().forEach(r=>{if(r.vehicle.toLowerCase().includes(q)||r.from.toLowerCase().includes(q)||r.to.toLowerCase().includes(q))results.push({type:'Маршрут',id:r.id,title:r.vehicle+' → '+r.to,section:'transport'})});getMaterials().forEach(m=>{if(m.name.toLowerCase().includes(q)||m.category.toLowerCase().includes(q))results.push({type:'Материал',id:m.id,title:m.name,section:'materials'})});getProcurements().forEach(p=>{if(p.name.toLowerCase().includes(q)||p.supplier.toLowerCase().includes(q))results.push({type:'Закупка',id:p.id,title:p.name,section:'procurement'})});g(S.users).forEach(u=>{if(u.login.toLowerCase().includes(q)||(u.displayName||'').toLowerCase().includes(q))results.push({type:'Пользователь',id:u.login,title:u.displayName||u.login,section:'dashboard'})});return results.slice(0,20)}

// ------ PDF (ГОСТ) ------
async function exportRequestPDF(id){const req=getRequests().find(r=>r.id===id);if(!req)return;const {jsPDF}=window.jspdf;const doc=new jsPDF();doc.setFontSize(16);doc.text('НАКЛАДНАЯ № '+req.id,20,20);doc.setFontSize(12);doc.text('Название: '+req.title,20,40);doc.text('Описание: '+req.desc,20,50);doc.text('Тип: '+req.type,20,60);doc.text('Статус: '+req.status,20,70);doc.text('Приоритет: '+req.priority,20,80);doc.text('Ответственный: '+(req.responsible||'—'),20,90);doc.text('Срок: '+(req.deadline||'—'),20,100);doc.text('Создал: '+req.creator,20,110);doc.text('Дата: '+new Date(req.created).toLocaleString(),20,120);doc.save('nakladnaya_'+req.id+'.pdf')}
async function exportRoutePDF(id){const route=getRoutes().find(r=>r.id===id);if(!route)return;const {jsPDF}=window.jspdf;const doc=new jsPDF();doc.setFontSize(16);doc.text('МАРШРУТНЫЙ ЛИСТ № '+route.id,20,20);doc.setFontSize(12);doc.text('Автомобиль: '+route.vehicle,20,40);doc.text('Тип: '+route.type,20,50);doc.text('Отправление: '+route.from,20,60);doc.text('Доставка: '+route.to,20,70);doc.text('Статус: '+route.status,20,80);doc.text('Дата: '+route.date,20,90);doc.save('marshrut_'+route.id+'.pdf')}
async function exportMaterialPDF(id){const mat=getMaterials().find(m=>m.id===id);if(!mat)return;const {jsPDF}=window.jspdf;const doc=new jsPDF();doc.setFontSize(16);doc.text('НАКЛАДНАЯ НА ВЫДАЧУ МАТЕРИАЛОВ',20,20);doc.setFontSize(12);doc.text('Материал: '+mat.name,20,40);doc.text('Категория: '+mat.category,20,50);doc.text('Ед. изм.: '+mat.unit,20,60);doc.text('Количество: '+mat.quantity,20,70);doc.text('Резерв: '+mat.reserve,20,80);doc.text('Доступно: '+(mat.quantity-mat.reserve),20,90);doc.save('nakladnaya_material_'+mat.id+'.pdf')}
async function exportProcurementPDF(id){const proc=getProcurements().find(p=>p.id===id);if(!proc)return;const {jsPDF}=window.jspdf;const doc=new jsPDF();doc.setFontSize(16);doc.text('ПРОТОКОЛ ЗАКУПКИ № '+proc.id,20,20);doc.setFontSize(12);doc.text('Название: '+proc.name,20,40);doc.text('Тип: '+(proc.type==='grant'?'Грант':proc.type==='competition'?'Конкурс':'Прямой договор'),20,50);doc.text('Поставщик: '+proc.supplier,20,60);doc.text('Сумма: '+(proc.amount?proc.amount.toLocaleString()+' руб.':'—'),20,70);doc.text('Статус: '+proc.status,20,80);doc.text('Дата: '+proc.date,20,90);if(proc.number)doc.text('Номер: '+proc.number,20,100);doc.save('protokol_zakupki_'+proc.id+'.pdf')}

// ------ НАСТРОЙКИ ------
function applySettings(){const settings=g(S.settings);if(settings.theme==='dark'){document.body.classList.add('mto-dark');document.getElementById('themeToggle').textContent='☀️'}else{document.body.classList.remove('mto-dark');document.getElementById('themeToggle').textContent='🌙'}if(settings.compact)document.body.classList.add('compact-mode');else document.body.classList.remove('compact-mode');if(!settings.animations)document.body.classList.add('no-anim');else document.body.classList.remove('no-anim');document.documentElement.style.setProperty('--font-size',(settings.fontSize||14)+'px')}

// ------ ОБНОВЛЕНИЕ ВСЕГО ------
function updateAll(){renderDashboard();renderTransport();renderRequests();renderMaterials();renderProcurements();renderSchedule();renderAudit();if(currentUser){userNameDisplay.textContent=currentUser.displayName||currentUser.login;logoutBtn.style.display='inline-block';document.querySelectorAll('.mto-nav a[data-section]').forEach(link=>{const sec=link.dataset.section;if(sec==='schedule'||sec==='audit'){link.style.display=isAdmin(currentUser)?'inline-block':'none'}else if(sec==='procurement'){const hasAccess=isAdmin(currentUser)||(currentUser.deptPath&&currentUser.deptPath.includes('Начальник склада'));link.style.display=hasAccess?'inline-block':'none'}else{link.style.display='inline-block'}});const roomKey=currentChatRoom==='personal'?'personal_'+currentUser.login:currentChatRoom;renderChat(roomKey);renderUserList();updateBurgerProfile()}else{userNameDisplay.textContent='Гость';logoutBtn.style.display='none'}populateDeptSelects();applySettings()}

function updateBurgerProfile(){const avatar=document.getElementById('burgerAvatar');const name=document.getElementById('burgerName');const role=document.getElementById('burgerRole');if(currentUser){if(currentUser.avatar){avatar.innerHTML='<img src="'+currentUser.avatar+'" alt="avatar">'}else{avatar.innerHTML='👤'}name.textContent=currentUser.displayName||currentUser.login;role.textContent=currentUser.position||getUserRole(currentUser)}else{avatar.innerHTML='👤';name.textContent='Гость';role.textContent='Не авторизован'}}

function renderUserList(){const users=g(S.users);const container=document.getElementById('userList');if(!container)return;container.innerHTML=users.filter(u=>u.login!==currentUser?.login).map(u=>'<div class="chat-room-item" data-room="personal_'+u.login+'" style="font-size:13px;padding:6px 12px;">'+(u.avatar?'<img src="'+u.avatar+'" style="width:24px;height:24px;border-radius:50%;object-fit:cover;">':'👤')+' '+(u.displayName||u.login)+'</div>').join('');container.querySelectorAll('.chat-room-item').forEach(el=>{el.addEventListener('click',function(){const room=this.dataset.room;switchChatRoom(room)})})}

function initAppAfterLogin(){if(!currentUser)return;populateDeptSelects();updateAll();document.getElementById('authOverlay').classList.add('hidden');document.querySelectorAll('.mto-nav a').forEach(a=>a.style.display='inline-block');const roomKey=currentChatRoom==='personal'?'personal_'+currentUser.login:currentChatRoom;renderChat(roomKey);renderUserList();updateBurgerProfile();populateAuditFilters()}

function populateAuditFilters(){const users=g(S.users);const userSelect=document.getElementById('auditFilterUser');userSelect.innerHTML='<option value="all">Все пользователи</option>';users.forEach(u=>{const opt=document.createElement('option');opt.value=u.login;opt.textContent=u.displayName||u.login;userSelect.appendChild(opt)});const actionSelect=document.getElementById('auditFilterAction');const actions=['Вход в систему','Выход','Регистрация','Создание заявки','Изменение заявки','Удаление заявки','Создание маршрута','Изменение маршрута','Удаление маршрута','Создание закупки','Изменение закупки','Удаление закупки','Добавление материала','Изменение материала','Удаление материала','Поставка материала','Резервирование материала','Выдача материала','Добавление ремонта','Завершение ремонта'];actionSelect.innerHTML='<option value="all">Все действия</option>';actions.forEach(a=>{const opt=document.createElement('option');opt.value=a;opt.textContent=a;actionSelect.appendChild(opt)})}

// ------ ОБРАБОТЧИКИ СОБЫТИЙ ------
document.querySelectorAll('.mto-nav a[data-section]').forEach(link=>{link.addEventListener('click',function(e){e.preventDefault();const sec=this.dataset.section;document.querySelectorAll('.mto-section').forEach(s=>s.classList.remove('active'));const target=document.getElementById('section-'+sec);if(target)target.classList.add('active');document.querySelectorAll('.mto-nav a').forEach(a=>a.classList.remove('active'));this.classList.add('active');if(sec==='requests')renderRequests();if(sec==='transport')renderTransport();if(sec==='materials')renderMaterials();if(sec==='procurement')renderProcurements();if(sec==='schedule')renderSchedule();if(sec==='audit')renderAudit();if(sec==='dashboard'){renderDashboard();fetchNews(5,'newsFeedList')}if(sec==='messenger'){const roomKey=currentChatRoom==='personal'?'personal_'+currentUser?.login:currentChatRoom;renderChat(roomKey);renderUserList()}})});

function updateClock(){document.getElementById('clock').textContent=new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}updateClock();setInterval(updateClock,10000);

document.getElementById('themeToggle').addEventListener('click',function(){document.body.classList.toggle('mto-dark');const isDark=document.body.classList.contains('mto-dark');this.textContent=isDark?'☀️':'🌙';const settings=g(S.settings);settings.theme=isDark?'dark':'light';s(S.settings,settings)});

logoutBtn.addEventListener('click',function(){logoutUser();currentUser=null;userNameDisplay.textContent='Гость';logoutBtn.style.display='none';document.getElementById('authOverlay').classList.remove('hidden');document.querySelectorAll('.mto-section').forEach(s=>s.classList.remove('active'));document.getElementById('section-dashboard').classList.add('active');document.querySelectorAll('.mto-nav a').forEach(link=>{if(link.dataset.section!=='dashboard')link.style.display='none';else link.style.display='inline-block'});showToast('Вы вышли','info')});

// ------ МОДАЛКА АУТЕНТИФИКАЦИИ ------
const authOverlay=document.getElementById('authOverlay');const authLogin=document.getElementById('authLogin');const authPassword=document.getElementById('authPassword');const authSubmit=document.getElementById('authSubmit');const authToggle=document.getElementById('authToggle');const authTitle=document.getElementById('authTitle');const authExtra=document.getElementById('authExtra');const authDeptPath=document.getElementById('authDeptPath');const authDisplayName=document.getElementById('authDisplayName');const authPhone=document.getElementById('authPhone');const authEmail=document.getElementById('authEmail');const authPosition=document.getElementById('authPosition');const authBirthDate=document.getElementById('authBirthDate');const authAvatarFile=document.getElementById('authAvatarFile');const authError=document.getElementById('authError');let isLoginMode=true;
function setAuthMode(mode){isLoginMode=(mode==='login');authTitle.textContent=isLoginMode?'Вход в систему':'Регистрация';authSubmit.textContent=isLoginMode?'Войти':'Зарегистрироваться';authToggle.textContent=isLoginMode?'Нет аккаунта? Зарегистрироваться':'Уже есть аккаунт? Войти';authExtra.style.display=isLoginMode?'none':'block';authError.textContent='';populateDeptSelects()}
function handleAuth(){const login=authLogin.value.trim();const password=authPassword.value.trim();if(!login||!password){authError.textContent='Заполните все поля';return}if(isLoginMode){if(loginUser(login,password)){authOverlay.classList.add('hidden');initAppAfterLogin()}else authError.textContent='Неверный логин или пароль'}else{const deptPath=authDeptPath.value;const displayName=authDisplayName.value.trim()||login;const phone=authPhone.value.trim();const email=authEmail.value.trim();const position=authPosition.value.trim();const birthDate=authBirthDate.value;let avatarBase64='';if(authAvatarFile.files.length>0){const reader=new FileReader();reader.onload=(e)=>{avatarBase64=e.target.result;if(registerUser(login,password,deptPath,displayName,phone,email,position,birthDate,avatarBase64)){loginUser(login,password);authOverlay.classList.add('hidden');initAppAfterLogin()}else authError.textContent='Пользователь уже существует'};reader.readAsDataURL(authAvatarFile.files[0]);return}if(registerUser(login,password,deptPath,displayName,phone,email,position,birthDate,avatarBase64)){loginUser(login,password);authOverlay.classList.add('hidden');initAppAfterLogin()}else authError.textContent='Пользователь уже существует'}}
authToggle.addEventListener('click',()=>setAuthMode(isLoginMode?'register':'login'));authSubmit.addEventListener('click',handleAuth);authLogin.addEventListener('keydown',e=>{if(e.key==='Enter')handleAuth()});authPassword.addEventListener('keydown',e=>{if(e.key==='Enter')handleAuth()});
document.getElementById('gosuslugiBtn').addEventListener('click',()=>oauthLogin('Госуслуги'));document.getElementById('mosruBtn').addEventListener('click',()=>oauthLogin('mos.ru'));

// ------ МОДАЛКА ЗАЯВКИ ------
const requestModal=document.getElementById('requestModal');const reqEditId=document.getElementById('reqEditId');const reqTitle=document.getElementById('reqTitle');const reqDesc=document.getElementById('reqDesc');const reqType=document.getElementById('reqType');const reqAddress=document.getElementById('reqAddress');const reqDept=document.getElementById('reqDept');const reqPriority=document.getElementById('reqPriority');const reqStatus=document.getElementById('reqStatus');const reqDeadline=document.getElementById('reqDeadline');const reqResponsible=document.getElementById('reqResponsible')||{value:''};const reqModalTitle=document.getElementById('reqModalTitle');
function openEditRequest(id){const reqs=getRequests();const req=reqs.find(r=>r.id===id);if(!req)return;reqEditId.value=id;reqTitle.value=req.title;reqDesc.value=req.desc;reqType.value=req.type;reqAddress.value=req.address||'';reqDept.value=req.deptPath;reqPriority.value=req.priority;reqStatus.value=req.status;reqDeadline.value=req.deadline||'';if(reqResponsible)reqResponsible.value=req.responsible||'';reqModalTitle.textContent='Редактирование заявки #'+id;requestModal.classList.remove('hidden');populateDeptSelects()}
document.getElementById('createReqBtn').addEventListener('click',function(){reqEditId.value='';reqTitle.value='';reqDesc.value='';reqType.value='repair';reqAddress.value='';reqDept.value=currentUser?currentUser.deptPath:'Диспетчерская';reqPriority.value='medium';reqStatus.value='new';reqDeadline.value='';if(reqResponsible)reqResponsible.value='';reqModalTitle.textContent='Создание заявки';requestModal.classList.remove('hidden');populateDeptSelects()});
document.getElementById('reqCancelBtn').addEventListener('click',()=>requestModal.classList.add('hidden'));
document.getElementById('reqSaveBtn').addEventListener('click',function(){const title=reqTitle.value.trim();const desc=reqDesc.value.trim();const type=reqType.value;const address=reqAddress.value.trim();const deptPath=reqDept.value;const priority=reqPriority.value;const status=reqStatus.value;const deadline=reqDeadline.value;const responsible=reqResponsible?reqResponsible.value:currentUser.login;if(!title){alert('Введите название');return}const id=reqEditId.value;if(id){updateRequest(parseInt(id),{title,desc,type,address,deptPath,priority,status,deadline,responsible})}else{if(!currentUser){alert('Не авторизован');return}createRequest(title,desc,type,address,deptPath,priority,status,deadline,currentUser.login,responsible)}requestModal.classList.add('hidden');renderRequests();updateAll()});

// ------ МОДАЛКА МАРШРУТА ------
const routeModal=document.getElementById('routeModal');const routeEditId=document.getElementById('routeEditId');const routeVehicle=document.getElementById('routeVehicle');const routeType=document.getElementById('routeType');const routeFrom=document.getElementById('routeFrom');const routeTo=document.getElementById('routeTo');const routeStatus=document.getElementById('routeStatus');const routeDate=document.getElementById('routeDate');const routeModalTitle=document.getElementById('routeModalTitle');
function openEditRoute(id){const routes=getRoutes();const route=routes.find(r=>r.id===id);if(!route)return;routeEditId.value=id;routeVehicle.value=route.vehicle;routeType.value=route.type;routeFrom.value=route.from;routeTo.value=route.to;routeStatus.value=route.status;routeDate.value=route.date;routeModalTitle.textContent='Редактирование маршрута #'+id;routeModal.classList.remove('hidden')}
document.getElementById('addRouteBtn').addEventListener('click',function(){routeEditId.value='';routeVehicle.value='ГАЗель NEXT';routeType.value='supply';routeFrom.value='';routeTo.value='';routeStatus.value='planned';routeDate.value=new Date().toISOString().split('T')[0];routeModalTitle.textContent='Добавление маршрута';routeModal.classList.remove('hidden')});
document.getElementById('routeCancelBtn').addEventListener('click',()=>routeModal.classList.add('hidden'));
document.getElementById('routeSaveBtn').addEventListener('click',function(){const vehicle=routeVehicle.value;const type=routeType.value;const from=routeFrom.value.trim();const to=routeTo.value.trim();const status=routeStatus.value;const date=routeDate.value;if(!from||!to){alert('Заполните адреса');return}const id=routeEditId.value;if(id){updateRoute(parseInt(id),{vehicle,type,from,to,status,date})}else{if(!currentUser){alert('Не авторизован');return}createRoute(vehicle,type,from,to,status,date)}routeModal.classList.add('hidden');renderTransport();updateAll()});

// ------ МОДАЛКА МАТЕРИАЛА ------
const materialModal=document.getElementById('materialModal');const matEditId=document.getElementById('matEditId');const matName=document.getElementById('matName');const matCategory=document.getElementById('matCategory');const matUnit=document.getElementById('matUnit');const matQuantity=document.getElementById('matQuantity');const matReserve=document.getElementById('matReserve');const matModalTitle=document.getElementById('matModalTitle');
function openEditMaterial(id){const mats=getMaterials();const mat=mats.find(m=>m.id===id);if(!mat)return;matEditId.value=id;matName.value=mat.name;matCategory.value=mat.category;matUnit.value=mat.unit;matQuantity.value=mat.quantity;matReserve.value=mat.reserve;matModalTitle.textContent='Редактирование материала';materialModal.classList.remove('hidden')}
document.getElementById('addMaterialBtn').addEventListener('click',function(){matEditId.value='';matName.value='';matCategory.value='Сантехника';matUnit.value='шт';matQuantity.value=0;matReserve.value=0;matModalTitle.textContent='Добавление материала';materialModal.classList.remove('hidden')});
document.getElementById('matCancelBtn').addEventListener('click',()=>materialModal.classList.add('hidden'));
document.getElementById('matSaveBtn').addEventListener('click',function(){const name=matName.value.trim();const category=matCategory.value;const unit=matUnit.value.trim();const quantity=parseInt(matQuantity.value)||0;const reserve=parseInt(matReserve.value)||0;if(!name||!unit){alert('Заполните название и единицу');return}const id=matEditId.value;if(id){updateMaterial(parseInt(id),{name,category,unit,quantity,reserve})}else{if(!currentUser){alert('Не авторизован');return}addMaterial(name,category,unit,quantity,reserve)}materialModal.classList.add('hidden');renderMaterials();updateAll()});

// ------ МОДАЛКА ПОСТАВОК ------
const suppliesModal=document.getElementById('suppliesModal');const suppliesList=document.getElementById('suppliesList');const supplyMaterialName=document.getElementById('supplyMaterialName');const supplyQuantity=document.getElementById('supplyQuantity');
document.getElementById('viewSuppliesBtn').addEventListener('click',function(){const supplies=getSupplies();if(!supplies.length)suppliesList.innerHTML='<p style="color:var(--text-secondary);">Нет поставок</p>';else suppliesList.innerHTML=supplies.slice(-20).reverse().map(s=>'<div style="padding:8px 0;border-bottom:1px solid rgba(0,0,0,0.04);"><strong>'+s.material+'</strong> +'+s.quantity+' <span style="color:var(--text-secondary);">'+s.date+'</span></div>').join('');suppliesModal.classList.remove('hidden')});
document.getElementById('addSupplyBtn').addEventListener('click',function(){const name=supplyMaterialName.value.trim();const qty=parseInt(supplyQuantity.value);if(!name||!qty||qty<=0){alert('Введите название и количество');return}addSupply(name,qty);supplyMaterialName.value='';supplyQuantity.value='';const supplies=getSupplies();suppliesList.innerHTML=supplies.slice(-20).reverse().map(s=>'<div style="padding:8px 0;border-bottom:1px solid rgba(0,0,0,0.04);"><strong>'+s.material+'</strong> +'+s.quantity+' <span style="color:var(--text-secondary);">'+s.date+'</span></div>').join('');renderMaterials()});
document.getElementById('suppliesCloseBtn').addEventListener('click',()=>suppliesModal.classList.add('hidden'));

// ------ МОДАЛКА ЗАКУПКИ ------
const procurementModal=document.getElementById('procurementModal');const procEditId=document.getElementById('procEditId');const procName=document.getElementById('procName');const procType=document.getElementById('procType');const procSupplier=document.getElementById('procSupplier');const procAmount=document.getElementById('procAmount');const procStatus=document.getElementById('procStatus');const procDate=document.getElementById('procDate');const procNumber=document.getElementById('procNumber');const procModalTitle=document.getElementById('procModalTitle');
function openEditProcurement(id){const procs=getProcurements();const proc=procs.find(p=>p.id===id);if(!proc)return;procEditId.value=id;procName.value=proc.name;procType.value=proc.type;procSupplier.value=proc.supplier;procAmount.value=proc.amount;procStatus.value=proc.status;procDate.value=proc.date;procNumber.value=proc.number||'';procModalTitle.textContent='Редактирование закупки #'+id;procurementModal.classList.remove('hidden')}
document.getElementById('addProcurementBtn').addEventListener('click',function(){procEditId.value='';procName.value='';procType.value='grant';procSupplier.value='';procAmount.value='';procStatus.value='planned';procDate.value=new Date().toISOString().split('T')[0];procNumber.value='';procModalTitle.textContent='Добавление закупки';procurementModal.classList.remove('hidden')});
document.getElementById('procCancelBtn').addEventListener('click',()=>procurementModal.classList.add('hidden'));
document.getElementById('procSaveBtn').addEventListener('click',function(){const name=procName.value.trim();const type=procType.value;const supplier=procSupplier.value.trim();const amount=parseFloat(procAmount.value);const status=procStatus.value;const date=procDate.value;const number=procNumber.value.trim();if(!name||!supplier){alert('Заполните название и поставщика');return}const id=procEditId.value;if(id){updateProcurement(parseInt(id),{name,type,supplier,amount,status,date,number})}else{if(!currentUser){alert('Не авторизован');return}createProcurement(name,type,supplier,amount,status,date,number)}procurementModal.classList.add('hidden');renderProcurements();updateAll()});

// ------ МОДАЛКА ПРОФИЛЯ ------
const profileModal=document.getElementById('profileModal');const profileLogin=document.getElementById('profileLogin');const profileDisplayName=document.getElementById('profileDisplayName');const profilePhone=document.getElementById('profilePhone');const profileEmail=document.getElementById('profileEmail');const profilePosition=document.getElementById('profilePosition');const profileBirthDate=document.getElementById('profileBirthDate');const profileAvatarFile=document.getElementById('profileAvatarFile');const profileAvatarPreview=document.getElementById('profileAvatarPreview');const profileDeptPath=document.getElementById('profileDeptPath');const profileNewPassword=document.getElementById('profileNewPassword');
function openProfile(){if(!currentUser)return;profileLogin.value=currentUser.login;profileDisplayName.value=currentUser.displayName||'';profilePhone.value=currentUser.phone||'';profileEmail.value=currentUser.email||'';profilePosition.value=currentUser.position||'';profileBirthDate.value=currentUser.birthDate||'';profileDeptPath.value=currentUser.deptPath||'Диспетчерская';profileNewPassword.value='';if(currentUser.avatar){profileAvatarPreview.src=currentUser.avatar;profileAvatarPreview.style.display='block'}else profileAvatarPreview.style.display='none';profileModal.classList.remove('hidden');populateDeptSelects()}
document.querySelector('.menu-item[data-burger="profile"]').addEventListener('click',function(){closeBurger();openProfile()});
document.getElementById('profileCancelBtn').addEventListener('click',()=>profileModal.classList.add('hidden'));
document.getElementById('profileSaveBtn').addEventListener('click',function(){const displayName=profileDisplayName.value.trim()||currentUser.login;const phone=profilePhone.value.trim();const email=profileEmail.value.trim();const position=profilePosition.value.trim();const birthDate=profileBirthDate.value;const deptPath=profileDeptPath.value;const newPassword=profileNewPassword.value.trim();let avatarBase64=currentUser.avatar||'';if(profileAvatarFile.files.length>0){const reader=new FileReader();reader.onload=(e)=>{avatarBase64=e.target.result;saveProfileData(displayName,phone,email,position,birthDate,deptPath,newPassword,avatarBase64)};reader.readAsDataURL(profileAvatarFile.files[0])}else saveProfileData(displayName,phone,email,position,birthDate,deptPath,newPassword,avatarBase64)});
function saveProfileData(displayName,phone,email,position,birthDate,deptPath,newPassword,avatar){const users=g(S.users);const idx=users.findIndex(u=>u.login===currentUser.login);if(idx!==-1){users[idx].displayName=displayName;users[idx].phone=phone;users[idx].email=email;users[idx].position=position;users[idx].birthDate=birthDate;users[idx].avatar=avatar;users[idx].deptPath=deptPath;if(newPassword)users[idx].password=newPassword;s(S.users,users);currentUser=users[idx];saveSession(currentUser);userNameDisplay.textContent=displayName;showToast('Профиль обновлён','success');profileModal.classList.add('hidden');updateAll()}}

// ------ МОДАЛКА НАСТРОЕК ------
const settingsModal=document.getElementById('settingsModal');const settingsDarkTheme=document.getElementById('settingsDarkTheme');const settingsNotifications=document.getElementById('settingsNotifications');const settingsCompact=document.getElementById('settingsCompact');const settingsAnimations=document.getElementById('settingsAnimations');const settingsLanguage=document.getElementById('settingsLanguage');const settingsFontSize=document.getElementById('settingsFontSize');
document.querySelector('.menu-item[data-burger="settings"]').addEventListener('click',function(){closeBurger();const settings=g(S.settings);settingsDarkTheme.checked=settings.theme==='dark';settingsNotifications.checked=settings.notifications!==false;settingsCompact.checked=settings.compact||false;settingsAnimations.checked=settings.animations!==false;settingsLanguage.value=settings.language||'ru';settingsFontSize.value=settings.fontSize||14;settingsModal.classList.remove('hidden')});
document.getElementById('settingsCancelBtn').addEventListener('click',()=>settingsModal.classList.add('hidden'));
document.getElementById('settingsSaveBtn').addEventListener('click',function(){const settings=g(S.settings);settings.theme=settingsDarkTheme.checked?'dark':'light';settings.notifications=settingsNotifications.checked;settings.compact=settingsCompact.checked;settings.animations=settingsAnimations.checked;settings.language=settingsLanguage.value;settings.fontSize=parseInt(settingsFontSize.value)||14;s(S.settings,settings);applySettings();showToast('Настройки сохранены','success');settingsModal.classList.add('hidden');updateAll()});

// ------ МОДАЛКА НОВОСТЕЙ ------
const newsModal=document.getElementById('newsModal');const newsList=document.getElementById('newsList');
document.querySelector('.menu-item[data-burger="news"]').addEventListener('click',function(){closeBurger();newsModal.classList.remove('hidden');(async()=>{const container=newsList;container.innerHTML='Загрузка...';try{const proxy='https://api.allorigins.win/raw?url=';const rss='https://news.yandex.ru/news.rss';const resp=await fetch(proxy+encodeURIComponent(rss));if(!resp.ok)throw new Error('Ошибка');const txt=await resp.text();const parser=new DOMParser();const xml=parser.parseFromString(txt,'text/xml');const items=xml.querySelectorAll('item');let html='';items.forEach(item=>{const title=item.querySelector('title')?.textContent||'Без названия';const pub=item.querySelector('pubDate')?.textContent||'';const link=item.querySelector('link')?.textContent||'#';html+='<div style="padding:12px;border-bottom:1px solid rgba(0,0,0,0.06);"><div style="font-weight:500;"><a href="'+link+'" target="_blank" style="color:var(--primary);text-decoration:none;">'+title+'</a></div><div style="font-size:13px;color:var(--text-secondary);">'+pub+'</div></div>'});container.innerHTML=html||'<p style="color:var(--text-secondary);">Новостей нет</p>'}catch(e){container.innerHTML='<p style="color:var(--text-secondary);">Не удалось загрузить новости</p>'}})()});
document.getElementById('newsCloseBtn').addEventListener('click',()=>newsModal.classList.add('hidden'));

// ------ МОДАЛКА ГОРЯЧЕЙ ЛИНИИ ------
const hotlineModal=document.getElementById('hotlineModal');document.querySelector('.menu-item[data-burger="hotline"]').addEventListener('click',function(){closeBurger();hotlineModal.classList.remove('hidden')});document.getElementById('hotlineCloseBtn').addEventListener('click',()=>hotlineModal.classList.add('hidden'));

// ------ БУРГЕР ------
const burgerPanel=document.getElementById('burgerPanel');const burgerBtn=document.getElementById('burgerBtn');const closePanel=document.getElementById('closePanel');
function toggleBurger(){burgerPanel.classList.toggle('open')}
function closeBurger(){burgerPanel.classList.remove('open')}
burgerBtn.addEventListener('click',toggleBurger);closePanel.addEventListener('click',closeBurger);document.addEventListener('click',function(e){if(!burgerPanel.contains(e.target)&&e.target!==burgerBtn)closeBurger()});document.querySelector('.menu-item[data-burger="close"]').addEventListener('click',closeBurger);

// ------ МЕССЕНДЖЕР ------
chatRooms.forEach(room=>{room.addEventListener('click',function(){const roomId=this.dataset.room;switchChatRoom(roomId)})});
chatSendBtn.addEventListener('click',async function(){const text=chatInput.value.trim();if(text){await sendChatMessage(text);chatInput.value=''}});
chatInput.addEventListener('keydown',async function(e){if(e.key==='Enter'){const text=this.value.trim();if(text){await sendChatMessage(text);this.value=''}}});
document.getElementById('chatPhotoBtn').addEventListener('click',()=>handleMediaCapture('image'));
document.getElementById('chatVideoBtn').addEventListener('click',()=>handleMediaCapture('video'));
document.getElementById('chatAudioBtn').addEventListener('click',()=>handleMediaCapture('audio'));
document.getElementById('voiceRecordBtn').addEventListener('click',toggleVoiceRecord);

// ------ ФИЛЬТРЫ ------
document.getElementById('matCategoryFilter').addEventListener('change',renderMaterials);
document.getElementById('routeFilterStatus').addEventListener('change',renderRoutes);
document.getElementById('reqFilterStatus').addEventListener('change',renderRequests);
document.getElementById('reqFilterType').addEventListener('change',renderRequests);
document.getElementById('procurementFilterStatus').addEventListener('change',renderProcurements);
document.getElementById('auditSearch').addEventListener('input',renderAudit);
document.getElementById('auditFilterUser').addEventListener('change',renderAudit);
document.getElementById('auditFilterAction').addEventListener('change',renderAudit);

// ------ ПОГОДА ------
document.getElementById('weatherUpdateBtn').addEventListener('click',function(){const city=document.getElementById('weatherCityInput').value.trim()||'Moscow';fetchWeather(city)});

// ------ КНОПКИ PDF (экспорт) ------
document.getElementById('exportRequestsPDF').addEventListener('click',function(){const reqs=getRequests();if(!reqs.length){showToast('Нет заявок для экспорта','error');return}exportRequestPDF(reqs[0].id)});
document.getElementById('exportRoutesPDF').addEventListener('click',function(){const routes=getRoutes();if(!routes.length){showToast('Нет маршрутов для экспорта','error');return}exportRoutePDF(routes[0].id)});
document.getElementById('exportMaterialsPDF').addEventListener('click',function(){const mats=getMaterials();if(!mats.length){showToast('Нет материалов для экспорта','error');return}exportMaterialPDF(mats[0].id)});
document.getElementById('exportProcurementPDF').addEventListener('click',function(){const procs=getProcurements();if(!procs.length){showToast('Нет закупок для экспорта','error');return}exportProcurementPDF(procs[0].id)});
document.getElementById('exportAuditPDF').addEventListener('click',function(){const logs=g(S.audit);if(!logs.length){showToast('Нет записей аудита','error');return}const {jsPDF}=window.jspdf;const doc=new jsPDF();doc.setFontSize(16);doc.text('ЖУРНАЛ АУДИТА',20,20);doc.setFontSize(10);let y=30;logs.slice(-30).reverse().forEach(l=>{doc.text(l.time+' | '+l.user+' | '+l.action+' | '+(l.details||''),20,y);y+=8;if(y>270){doc.addPage();y=30}});doc.save('audit.pdf')});

// ------ ПОИСК (кнопка) ------
document.getElementById('searchBtn').addEventListener('click',function(){const query=document.getElementById('globalSearch').value.trim();if(!query){showToast('Введите запрос','info');return}const results=globalSearch(query);if(results.length){showToast('Найдено '+results.length+' результатов','info');console.log(results)}else showToast('Ничего не найдено','error')});

// ------ СОХРАНЕНИЕ РАСПИСАНИЯ ------
document.getElementById('saveScheduleBtn').addEventListener('click',function(){const selects=document.querySelectorAll('.schedule-select');selects.forEach(sel=>{const user=sel.dataset.user;const day=sel.dataset.day;const val=sel.value;const schedule=getSchedule();if(!schedule[user])schedule[user]={};schedule[user][day]=val;saveSchedule(schedule)});showToast('Расписание сохранено','success')});

// ------ ЗАПУСК ------
if(loadSession()){initAppAfterLogin();authOverlay.classList.add('hidden')}else{authOverlay.classList.remove('hidden');setAuthMode('login');document.querySelectorAll('.mto-nav a').forEach(link=>{if(link.dataset.section!=='dashboard')link.style.display='none';else link.style.display='inline-block'});statsContainer.innerHTML='';recentOrders.innerHTML='';kpiGrid.innerHTML='';activityList.innerHTML='';erpLogItems.innerHTML='';transportGrid.innerHTML='';routesBody.innerHTML='';auditBody.innerHTML='';requestsBody.innerHTML='';materialsBody.innerHTML='';procurementBody.innerHTML='';scheduleContainer.innerHTML='';chatMessagesContainer.innerHTML='';repairContainer.innerHTML='';userNameDisplay.textContent='Гость';logoutBtn.style.display='none';populateDeptSelects();fetchNews(5,'newsFeedList');setTimeout(initMaps,1000)}
window.addEventListener('resize',()=>{setTimeout(initMaps,300)});
console.log('МТО v4.0 – полная версия с правами, PDF, расписанием, ремонтом, грантами и улучшенным интерфейсом загружена!');

})();